require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

def common_pods
    config = use_native_modules!
    use_react_native!(:path => config["reactNativePath"])
    # pod 'FBLazyVector', :path => '../node_modules/react-native/Libraries/FBLazyVector'
    # pod 'FBReactNativeSpec', :path => '../node_modules/react-native/Libraries/FBReactNativeSpec'
    # pod 'RCTRequired', :path => '../node_modules/react-native/Libraries/RCTRequired'
    # pod 'RCTTypeSafety', :path => '../node_modules/react-native/Libraries/TypeSafety'
    # pod 'React', :path => '../node_modules/react-native'
    # pod 'React-Core', :path => '../node_modules/react-native'
    # pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
    # pod 'React-Core/DevSupport', :path => '../node_modules/react-native'
    # pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native'
  
    # pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
    # pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
    # pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
    # pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
    # pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
    # pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
    # pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
    # pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
    # pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  
    # pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
    # pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
    # pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
    # pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
    # pod 'ReactCommon/turbomodule/core', :path => '../node_modules/react-native/ReactCommon'
    # pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
    # # Third party deps podspec link
    # pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    # pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    # pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
end

target 'ViroReact' do
    common_pods
end

target 'ViroReact_static_lib' do
    common_pods
end

target 'ViroReact_release_tests' do
    common_pods
end
