require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

def common_pods
    config = use_native_modules!
    use_react_native!(:path => config["reactNativePath"])
end

target 'ViroReact' do
    common_pods
end

target 'ViroReact_static_lib' do
    common_pods
end

target 'ViroReact_release_tests' do
    common_pods
end
