name: Viro Bridge CI Pipeline
on: [push]
jobs:
  bridge_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      # Setup dependencies for React Native
      # Note, brew and node are already installed on github workflows.
      - name: Setup Watchman
        run: brew install watchman
      - name: ViroReact Npm Install
        run: npm install
        working-directory: ./
      - name: ViroReact Pods Install
        run: pod install
        working-directory: ./ios

      - name: xcodebuild ViroReact IOS framework
        working-directory: ./ios
          xcodebuild \
          -workspace ViroReact.xcworkspace/ \
          -scheme ViroReact_static_lib \
          -sdk iphoneos \
          -configuration Debug \
          -UseModernBuildSystem=NO

      # Prepare Release scripts should also run our gradle builds
      # required for Android RN Frameworks.
      - name: Prepare Release
        run: ./prepare_release.sh

      - name: Upload tgz Artifact
        uses: actions/upload-artifact@v1
        with:
          name: react-viro-2.18.0.tgz
          path: ./react-viro-2.18.0.tgz
